# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-17 09:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventId', models.IntegerField()),
                ('eventName', models.TextField()),
                ('eventDescription', models.TextField()),
                ('eventDate', models.DateField()),
                ('eventTime', models.TimeField()),
                ('isOpenToAll', models.BooleanField()),
                ('eventDuration', models.TextField()),
                ('eventVenue', models.TextField()),
            ],
        ),
    ]
