# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-06 09:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.TextField()),
                ('firstName', models.TextField()),
                ('lastName', models.TextField()),
                ('address', models.TextField()),
                ('email', models.TextField()),
                ('phone', models.TextField()),
                ('membershipExpiry', models.DateField()),
                ('familyCount', models.IntegerField()),
            ],
        ),
    ]
