# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-05-06 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpc', '0002_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='upcomingEvent',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
